branding = "fiberos"
dont-chroot = false
quit-at-end = true

[paths]  # optional; keeps things explicit
modules-search  = ["/etc/calamares/modules", "/usr/share/calamares/modules"]
branding-search = ["/etc/calamares/branding", "/usr/share/calamares/branding"]

[[sequence]]
type = "show"
modules = [
	"welcome",
	"locale",
	"keyboard",
	"partition",
	"users",
	"summary"
]

[[sequence]]
type = "exec"
modules = [
	"partition",
	"mount",
	"shellprocess@fiberos-genconfig",
	"shellprocess@fiberos-install",
	"umount"
]

[[sequence]]
type = "show"
modules = [ "finished" ]
